VERSION="2.0.0" NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

ACCOUNTS=[ 
"GCAGQSW6TYDAP3AVOWKJVFFP5FGDYXVHEZRM2Q5KVNDOFFGJHI2G6OZA", 
"GBLF4PSXHKNFUMGO2K2OHY57STC32K7OZHBTYXY3L6KILPEHDEFO3LD3" 
] 

[DOCUMENTATION] 
ORG_NAME="MARFIL" 
ORG_LOGO="https://github.com/plexoassets/lexo/blob/main/XS.png" 
ORG_DESCRIPTION="Plexo es una empresa del sector cultural dedicada a la produccion y realizacion de eventos" 
ORG_PHYSICAL_ADDRESS="SPAIN" 
ORG_OFFICIAL_EMAIL="plexo@plexo.cat"
ORG_URL="https://github.com/plexoassets/lexo"

[[CURRENCIES]] 
code="LEXO" 
issuer="GCAGQSW6TYDAP3AVOWKJVFFP5FGDYXVHEZRM2Q5KVNDOFFGJHI2G6OZA" 
display_decimals=6 
is_asset_anchored=false 
name="LEX"
desc="Un token para utilizar en eventos como forma de pago, premios o recompensas, intercambio, etc" 
conditions="Hay 1.000.000.000 LEX. Se distribuiran de diferente manera entre los usuarios de la red de Plexo" 
image="https://github.com/plexoassets/lexo/blob/main/XS.png"
# LEX (LEXO) Token was issued using the open and inclusive Stellar blockchain network. 
# Home Domain: github.com/plexoassets/lexo
# LEX Token
