# MARFIL stellar.toml

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

DOMAIN="https://plexo.cat"

URI_REQUEST_SIGNING_KEY="GBLF4PSXHKNFUMGO2K2OHY57STC32K7OZHBTYXY3L6KILPEHDEFO3LD3"

ACCOUNTS=[
"GC2ARUBS34AZ3FPITHGTEI2EIEWIRDVEP2RADPA5IMAB33RQOEAESL23",
"GBLF4PSXHKNFUMGO2K2OHY57STC32K7OZHBTYXY3L6KILPEHDEFO3LD3"]

[DOCUMENTATION]
ORG_NAME="MARFIL"
ORG_URL="https://marfiltkn.wordpress.com"
ORG_LOGO="https://marfiltkn.files.wordpress.com/2021/12/marfil02.png"
ORG_DESCRIPTION="ART & CULTURE ORGANIZATION"
ORG_OFFICIAL_EMAIL="marfiltkn@gmail.com"

[[CURRENCIES]]
code="MARFIL"
name="MARFIL"
issuer="GC2ARUBS34AZ3FPITHGTEI2EIEWIRDVEP2RADPA5IMAB33RQOEAESL23"
desc="EXPERIMENTAL TOKEN."
image="https://marfiltkn.files.wordpress.com/2021/12/marfil02.png"
status="live"
display_decimals=5
fixed_number=30000000

[[PRINCIPALS]]
email="marfiltkn@gmail.com"

# MARFIL (MARFIL) Token was issued using the open and inclusive Stellar blockchain network.
# Home Domain: plexo.cat
# MARFIL Token
